txgh:
  github:
    repos:
      <%= ENV['TX_PUSH_TRANSLATIONS_TO'] %>:
        api_username: "<%= ENV['GITHUB_USERNAME'] %>"
        api_token: "<%= ENV['GITHUB_TOKEN'] %>"
        push_source_to: "<%= ENV['GITHUB_PUSH_SOURCE_TO'] %>"
        branch: "<%= ENV['GITHUB_BRANCH'] %>"
        webhook_secret: "<%= ENV['GITHUB_WEBHOOK_SECRET'] %>"
      LMMS/lmms.io:
        api_username: "<%= ENV['GITHUB_USERNAME'] %>"
        api_token: "<%= ENV['GITHUB_TOKEN'] %>"
        push_source_to: "lmms/lmmsio"
        branch: "<%= ENV['GITHUB_BRANCH'] %>"
        webhook_secret: "<%= ENV['GITHUB_WEBHOOK_SECRET'] %>"
  transifex:
    projects:
      <%= ENV['GITHUB_PUSH_SOURCE_TO'] %>:
        tx_config: "<%= ENV['TX_CONFIG_PATH'] %>"
        api_username: "<%= ENV['TX_USERNAME'] %>"
        api_password: "<%= ENV['TX_PASSWORD'] %>"
        push_translations_to: "<%= ENV['TX_PUSH_TRANSLATIONS_TO'] %>"
        push_trigger: "<%= ENV['TX_PUSH_TRIGGER_REVIEWED_OR_TRANSLATED'] %>"
        webhook_secret: "<%= ENV['TX_WEBHOOK_SECRET'] %>"
